# Generated by Django 5.0.6 on 2026-07-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='time_expired',
            field=models.BooleanField(default=False),
        ),
    ]
