# Generated by Django 5.0.6 on 2026-07-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_realinterviewreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='realinterviewreport',
            name='questions_reward_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
