# Generated by Django 5.0.6 on 2026-08-08 00:00

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0007_realinterviewreport_questions_reward_granted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="realinterviewreport",
            name="round_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name="realinterviewreport",
            constraint=models.UniqueConstraint(
                fields=["user", "company_name", "round_name"],
                condition=Q(had_recent_interview="yes"),
                name="unique_real_report_per_user_company_round",
            ),
        ),
    ]
