# Generated by Django 5.0.6 on 2026-07-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_paymentorder_topup_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_domain', models.CharField(help_text='e.g. thapar.edu — students with this email domain are covered.', max_length=255, unique=True)),
                ('granted_plan', models.CharField(choices=[('pro', 'Pro'), ('premium', 'Premium'), ('max', 'Max')], max_length=20)),
                ('interview_limit', models.PositiveIntegerField(default=20, help_text="Interviews allowed per cycle, independent of granted_plan's own monthly limit.")),
                ('cycle_days', models.PositiveIntegerField(default=30)),
                ('sponsor_covers_until', models.DateTimeField(help_text='Coverage ends at this moment unless extended (e.g. the college pays for another cycle).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
