# Generated by Django 5.0.6 on 2026-08-11 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_sponsorshipcampaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorshipcampaign',
            name='email_domain',
            field=models.CharField(blank=True, default='', help_text='e.g. thapar.edu — everyone with this email domain is covered. Leave blank for a campaign that covers only the uploaded email list.', max_length=255),
        ),
        migrations.CreateModel(
            name='SponsorshipMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='subscriptions.sponsorshipcampaign')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.AddConstraint(
            model_name='sponsorshipmember',
            constraint=models.UniqueConstraint(fields=('campaign', 'email'), name='unique_email_per_campaign'),
        ),
    ]
