# Generated by Django 5.0.6 on 2026-07-12 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_bonus_interviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_cycle_start',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Start of the current 30-day usage cycle.'),
        ),
    ]
