# Generated by Django 5.0.6 on 2026-07-30 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_current_cycle_start'),
        ('subscriptions', '0004_sponsorshipcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sponsorship_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='subscriptions.sponsorshipcampaign'),
        ),
        migrations.AddField(
            model_name='user',
            name='sponsorship_cycle_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sponsorship_interviews_used',
            field=models.IntegerField(default=0),
        ),
    ]
