# Generated by Django 5.0.6 on 2026-08-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=30)),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
    ]
