# Generated by Django 5.0.6 on 2026-07-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_kind_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('system_design', 'System Design'), ('hr', 'HR')], default='technical', help_text='Drives the badge/styling on the frontend round picker.', max_length=20),
        ),
    ]
