# Generated by Django 5.0.6 on 2026-07-29 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_backfill_round_type'),
        ('interviews', '0007_realinterviewreport_questions_reward_granted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='source_report',
            field=models.ForeignKey(blank=True, help_text='The real-interview-report submission this question came from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_questions', to='interviews.realinterviewreport'),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text="Candidate-submitted questions start 'pending' until an admin verifies them.", max_length=10),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='submitted_company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='submitted_role_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='submitted_round_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('coding', 'Coding'), ('behavioral', 'Behavioral'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='companies.round'),
        ),
    ]
