# Generated by Django 5.0.6 on 2026-08-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_interviewquestion_source_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='language',
            field=models.CharField(blank=True, default='javascript', help_text='Coding questions only: editor syntax-highlighting language.', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='starter_code',
            field=models.TextField(blank=True, help_text='Coding questions only: function stub pre-filled into the code editor.'),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('coding', 'Coding'), ('system_design', 'System Design'), ('behavioral', 'Behavioral'), ('other', 'Other')], max_length=20),
        ),
    ]
