# Generated by Django 5.0.6 on 2026-08-13 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_interviewquestion_language_and_more'),
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="Set only for kind='enterprise' rows: the org this private question bank belongs to. Public companies/skills endpoints always exclude rows with this set — see apps.companies.views.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='enterprise.organization'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kind',
            field=models.CharField(choices=[('company', 'Company'), ('skill', 'Skill'), ('enterprise', 'Enterprise (org-private)')], default='company', help_text="'company' = a real company interview. 'skill' = a skill-based practice interview.", max_length=10),
        ),
    ]
