# Generated by Django 5.0.6 on 2026-08-13 20:15

import apps.enterprise.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0008_interviewquestion_language_and_more'),
        ('interviews', '0008_realinterviewreport_round_name_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('candidate_quota', models.PositiveIntegerField(default=50, help_text="Total proctored interviews this org's contract covers.")),
                ('candidates_used', models.PositiveIntegerField(default=0)),
                ('contract_ends', models.DateTimeField(help_text='Org access is disabled once this passes, unless extended.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('recruiter', 'Recruiter')], default='admin', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='enterprise.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgCandidateInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=apps.enterprise.models._generate_invite_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='enterprise.organization')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_invites', to='companies.round')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_invite', to='interviews.interviewsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('no_face', 'No face detected'), ('multiple_faces', 'Multiple faces detected'), ('gaze_away', 'Looking away'), ('tab_switch', 'Tab switch / left fullscreen'), ('low_light', 'Low light / camera obscured'), ('other', 'Other')], max_length=20)),
                ('confidence', models.FloatField(default=0.0, help_text='Client-reported detection confidence, 0-1.')),
                ('clip', models.FileField(blank=True, help_text='Short clip captured around this event, if the event severity warranted one.', null=True, upload_to='proctoring_clips/%Y/%m/')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to='interviews.interviewsession')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='organizationmember',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_user_per_organization'),
        ),
    ]
