# Generated by Django 5.0.6 on 2026-08-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringevent',
            name='note',
            field=models.CharField(blank=True, help_text="Short client-supplied reason, mainly for event_type=other (e.g. 'paste', 'devtools').", max_length=200),
        ),
    ]
