# Generated by Django 5.0.6 on 2026-08-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_proctoringevent_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoringevent',
            name='event_type',
            field=models.CharField(choices=[('no_face', 'No face detected'), ('multiple_faces', 'Multiple faces detected'), ('gaze_away', 'Looking away'), ('tab_switch', 'Tab switch / left fullscreen'), ('low_light', 'Low light / camera obscured'), ('phone_detected', 'Phone or device detected on camera'), ('other', 'Other')], max_length=20),
        ),
    ]
