# Generated by Django 5.0.6 on 2026-08-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0003_alter_proctoringevent_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="live_camera_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Superuser-only. Lets this org's members watch a candidate's live camera feed during their interview.",
            ),
        ),
    ]
